package leetcode;

/**
 * https://leetcode.com/problems/longest-repeating-character-replacement/
 */
public class Problem424 {
//    public int characterReplacement(String s, int k) {
//        int max = 0;
//        for (int i = 0; i < s.length(); i++) {
//            int tmpMax = 0;
//            char c1 = s.charAt(i);
//            int idx = i;
//            int j = 0;
//            while (idx < s.length() && j < k) {
//                char c2 = s.charAt(idx);
//                if (c1 != c2) {
//                    j++;
//                }
//                tmpMax++;
//                idx++;
//            }
//            while (idx < s.length() && s.charAt(idx++) == c1) {
//                tmpMax++;
//            }
//            idx = i - 1;
//            while (idx >= 0 && j < k) {
//                char c2 = s.charAt(idx);
//                if (c1 != c2) {
//                    j++;
//                }
//                tmpMax++;
//                idx--;
//            }
//            while (idx >= 0 && s.charAt(idx--) == c1) {
//                tmpMax++;
//            }
//            max = Math.max(tmpMax, max);
//        }
//        return max;
//    }

    public int characterReplacement(String s, int k) {
        int max = 0;
        for (int i = 0; i < s.length(); i++) {
            int[] counts = new int[26];
            int sum = 0;
            int j = 0;
            for (; j < s.length(); j++) {
                char c = s.charAt(j);
                if (counts[c - 'A'] == 0) {
                    sum++;
                }
                counts[c - 'A']++;
                if (k + 1 - sum == 0) {
                    break;
                }
            }
            j++;
            if (j < s.length()) {
                char c1 = s.charAt(j);
                if (counts[c1 - 'A'] > 0) {
                    counts[c1 - 'A']++;
                    while (j++ < s.length()) {
                        char c2 = s.charAt(j);
                        if (c1 == c2) {
                            counts[c1 - 'A']++;
                        } else {
                            break;
                        }
                    }
                }
            }
            int length = 0;
            for (int count : counts) {
                length += count;
            }
            max = Math.max(max, length);
//            int tmpMax = 0;
//            char c1 = s.charAt(i);
//            int idx = i;
//            int j = 0;
//            while (idx < s.length() && j < k) {
//                char c2 = s.charAt(idx);
//                if (c1 != c2) {
//                    j++;
//                }
//                tmpMax++;
//                idx++;
//            }
//            while (idx < s.length() && s.charAt(idx++) == c1) {
//                tmpMax++;
//            }
//            idx = i - 1;
//            while (idx >= 0 && j < k) {
//                char c2 = s.charAt(idx);
//                if (c1 != c2) {
//                    j++;
//                }
//                tmpMax++;
//                idx--;
//            }
//            while (idx >= 0 && s.charAt(idx--) == c1) {
//                tmpMax++;
//            }
//            max = Math.max(tmpMax, max);
        }
        return max;
    }

    public static void main(String[] args) {
        Problem424 prob = new Problem424();
//        System.out.println(prob.characterReplacement("ABAAACD", 2)); // 6
//        System.out.println(prob.characterReplacement("ABAB", 2)); // 4
//        System.out.println(prob.characterReplacement("AABABBA", 1)); // 4
//        System.out.println(prob.characterReplacement("AABAABBA", 1)); // 5
//        System.out.println(prob.characterReplacement("ACABD", 2)); // 4
//        System.out.println(prob.characterReplacement("ABBB", 2)); // 4
        System.out.println(prob.characterReplacement("ABBBBABABBC", 2)); // 9
//        System.out.println(prob.characterReplacement("ABCD", 4)); // 4
//        System.out.println(prob.characterReplacement("ABCDDE", 4)); // 6
//        System.out.println(prob.characterReplacement("WBRIQCVFYHTSFAJVVSUBLQYBSMUWULUKUAMUSDTVJRWSSYRXTSCIYUDTGOCWRJHBURWQYENEEYVCHVIKBYBQJUGRWVLFORNVSISGDNZREMWMUWXWWRMPBNZAPSFDSGVCGJPEDUCWBMGEZCWUVNKFTFONIKHWGYPFGMEIKMYFRVDDTPEZLUHZIHVKBWGMUUDYBTXZCIRVOAWZTSEZUTJNDXJSWXZZTXPNTCNDPPWLXEHJPZVKAYMHYDNQRMIPEIRJNGYZQCIQSWRQSLSFENBTEABYWJIQNDMQHXMWALFKQBFWWNKSVDIZHLSAQWEQKHFFOUECQVUDMYNFUYBMROIGKLKPYIWSBBORHGLQOTJSOOIABZAJVPDUHHHUIXQBCWVSMVGSOGDVDILBJEFNIPSNNODGTWFHCPYBETOEYXEUDHGJDYMUAXLSIHDCDBVZUWFOMKOJGWTXEPOSTTUXJATSJJACDQYBLWNWOAGZQEQQZKVEKMMYARXHQXRLNAUMPDFSCODEFPFVKIJRYFYNBNRAXGDIEWDPVCRPQRZKWUKKSGFHIVFVHSUEYALRENJVBEQINQASMBRXLRPKXNHCZRVMVSOSJDRJHZIWMCLOTKNYVTRDPNUEJLMIAHFLLWUQLUZQVDUBRAHJOFSSAMOJOAYLKEGCJGTRKHHRZJTTBLGCUMLTKILXNYOTGZQWCKOJLLVTGSSRHDPPRLMXFNILNJPHMIWJKKHJNJRLQTVFKBKAJZMDVTXPGXHOONEYUXVILSEGSJKHLHCFGCAZMWYXFUMNWHIYGZFRZPRJTVBEXCFFGULMZSDRZAVWUVDQCTXZBHFAPOZQCRKVHWWYEALJBYDGMIEEXDDFZYEBUHUEZMZALGZAHHAECPMEGDRMVZZNQRQULRNRABQUOIEGXLNOZUFQJKDKGCZFVIPBIRNQBEERWMTWUBIGFUHKRQVACWPGFHFAPFBZMQXEYGWRBWZEQEHXXCUAJWEECFNHXRWFQUPMOQEEZWRPRHILZVCCWDTFZETWABPEKWCBDIHEAZKVNQOOOGQVGHTTUFCAFWHMECOSZKTHQXPORBGXLVDETCBIDIOYSZNPOXUKHSFBLSWVBXQOPFSTLVQPSIKKGUFCDCKVBSMAAEGUDFUXJAFQYVVTKEEQUUXJQMSGXGWEUELFFFVEHRDPZKBVNUQZOTMXIZFXCURFDSWINGWIAPLHLXZDOMNMMSYNNKAFNGLVOBYERFMSGLNNFDXWGHKADQVLIQHITXFBYTORPZYBWQEBNTCETQHVLMCHDHNQEUQWLCGDKXUHSQIILMHVFQIJMWSEXTLNRWMRDUAEEHNYTCWKWIGRASCAVRBSZEYHJXXWQAILZXHZQNOEUQIYPGXRRMCAFBOPTQFJIDWUUIMTBESCAJYMPDJGPGHFEXLPGJLDJIWMROJISDHZUYOMWQEWYTPHDMYYUKZWZFIGOACLZVYMKTMAHHGNHRMFBLPDWUPVZXHJPJAAFYFGMSRSQKWXKOWMPNTZPUBYJYIPMRERSTWHEDSXXJGHHMWYRNBEGYVHUQVVELAORPJWLECIKPPPNTGCJFBJNZGXCCTUNOJMZLXDTIWDDHBMBXXUUMWNJSNPVPKKEDWRPIATEAVHFONBVYVWCSIYPKFCIIMXKPYWKCXLQGKQNXDKKHGSTIWAMGDLXJCYFQNOLKVRPBUMNTQYZHACFZFGGWQIJRSAVKDXHHKQODGBEBFLPIESJEQQFXOVXORDPREKPDHMYSXAQCSSBPIQTFJCDRDOFQUHHHJKIRAPJACSFWVUBDJMQBJFNFFXXSLOBJFTMBBILIBFQOUMCQXMQHXNICXDXYKXEAAHVYSUHAYQKEPLQXVJYFFNWZRXXVWUNTQGWYURBJIHTSPIMCVHXIQIGQZJAVNYIFRYNPNYMQNYBQIGFOYGHOZBBHDYQMSYPSMAXZOWMAGWVXDAXNCTBRLQPOTRSPUHWSXLJVRKRCBZRAYWZHAFZXONWTMNQDDYVZAPOPHUHOJGRSHBJLXLTOMRGJLZDBVTKIWJHAQXFXAZSANBVQCIYPLBSSYULGOARKRKDSHSWOYCAEQGWEZQXWHTWSHGVOBBKAYBUMJORLVAPLQZYVFIGREYEUGUHDJYCLVXFBURBPFRSFOISPTCTRFULTBZPBZNWRRWJXSYYEAAKCRNGNFWSZDFTUIZVNVYPDMGXATHULMMSLQQHYTWOOTIFJIERABJPAUQAQVFUBGIHJTBIVAFNALLKKGRCNIONHOATUZNROWTRJCYVYLCWCPDUQEBTERIBDARVZPQJBUUJOAIYPYIUWXFCAQOLEMWVEMUWXGSOZJRAAAUVDCODWQONAEBQKNPAPCBHCNQAVRCNOBWSPCKVSUQHHNWGUTIHUDCEKMLHOCWHMKPYBGTQYKXSSIAMBMKLWZMGQLNAMAUDKQZTNUTZJWBBQUTWAUQMQMXTJHERZGYIAOGHALPDUUXVAQJFTDWVLJAHDNGGHDELGPNUYJKGLFNUFVQOKXNDDIMLEWHOKPKLWSGTHBDQGQQIVTRKNSSLPVCQPGWZPLKMWTPWOMWCKLFKHDDOBOUQVHJENRGVJBNCJVJDQYEDBSVOEXPJVYYWIMVXLXAEVFHURSJIMNJQGVDSMREMQGOKXAFWMMFGSMZBIVGIOHWKCHYPDRQEUDFBDKQFQPOEILESIULDPSKYYOJYIQCKPZSIBPNQIZCWJHCUZSEJOXWGUKXPAWXJPSFFDPANHLEAXAUMOTOZTCNBSBPGLJSWJATQFOJTNGPCSGXOFYCSKBLALTPNVODVZSDLIYACERBYLACMDIESPMTFVBWGSYDOZXTTKVWXWGWBGAGNQLZNWWJFOTJRAOKHGRUTKFLRYUGOMHRSITXDJRSCRCDDRWKGVVXAUGPUUOPGSVXQSYAIUAQAKMZHRFHZZDTHRTRMFPGIWCZLSRIILSRMBRFSEMAVGLYVUAWQQCTEDUZDHCSMLUGDUVKUTPMIBYDEPNVPWUIZAZKEMOGRMLSITHOUYBZBJWTMYBXLETPBIXCJQFIPVXOPKEEVNTJFVTYUGBDQJGTQFKNNEFIPUTITZRJBEMQZEPISAZBYFIMKKOWFMTRMTJTWVWPLYOXSKJDZUXAATGIOZDLCPJEGPUTBYAHJGLTZTOSRZZPQGNUWPUBFYGSDVSSYKZEOGJZMFUYBFDPORSJEGZTDVURPTMMQNMNQVFHIDMPGVKQKZKXVDMAJXOGXAOJJNXSNEOBEWUXGWNLTXZZPFRJYQNJICGDEFDIUOGWAOVTAGXNDVJRPHMZOKRZYMMNFAXYPTYZXITXADXDGVHEBEACVLPSOTAMLIVPHCSJWQKTSTCYKWETJDOYBXCHWCLGLBUTEHTRIPFTSYTMHHMXJBLFMLMIDDBGAZWSKFTIBDOUHOYYKTRKKVDFTSMTJWAHYEICILPFUDZEYFZLFWDZIXFORJCJJDLSDDOKNXTNIJHBDYFPTMGOGNJQJHNJTOXGVYBMVPZIUCANUODRIFUDWRZFSMZVHECLCHBVQWZSGOETPZHTPEYIYGDKERGBQMTTBAJVEIECMORZBWAOOVNTINTZIFPDOVSCFMUAGNGLVRZMUAHNEAFJNVPJUJWNENIMZMHQLXQTHDKZFTNISFGTNFNPKRDPBOEVPVNMRXRIQYZIBFAPMOHWOEXIEHSKABDTZDLBXCJJLZILVJBJCJGFPGBFZFNXDBUJWYSNYAUEQXTRDGUUKPHFKGQFNZUNWMIMJMROSPRZZIFVELXRWDZMDMYCDQEJYVZULVZCDPZGTPBFQORXGFPSOKMCHWMCLKOVPTRUBWETSPSBZKVREMQEIPTNQICTASVIHWROEZJNCFIQKBFNNABJGKWCSSBYMBOIKCADMOTWDBWAGXFDPMCLUURSQMMCVLBJZQAYUWNDYWBRAMSRPURRGVONEZTXELXJMASHSOBZLAUYEVIZIZJZPESNTIQTYVNGPRMHYCZWCMCYPXOBTZNWQRQDLUTNBDETJOBEWTEBMYAMYAEGNTNFHIWWRWQDUNMWUAFWOEDCINRXUIVPTODPGGEONSTXWEGEVBBLPFXVREHNNZQYLBRPNHHPUYSUTYOJHGKKQGSYPAUUUUHKSQHSUTZPHBTJSEQGLWSEADAGNQLIQDWVRMPHURXWPAOTIXMZFMSUCDZRJBNAGETGZSLYZHNORVSEFXGICAUUGKFNOIFPHVFZXZFZOANUBNGGUXUWZLVHWXLOLYCQNXODAWOAPTHZKKGSJAGYRYXEEAHDOYDOZUKSYKABDBGYPNLKOUGJWCVBDRNXWTCMUVKKGGABIJWVBEGNNWJHFURDMERBRNYCMZGLLHJRBBYOTQWAEBFQSWZLPEYUZJVGVHJZJMRTKUKAOWHUWBZLKKPEMMDXHCKTXMENLLNCQOEIDFAWRSBVNZDKDFFPRBYKTAOVQEMBVPANILXCHYOEEFQBEYXBWAGEUWHBQLAPIDBAYGXYWVYXWVPUIAJLMFUTWDNEQHYXCVPFADXNIIBQOKRYVTFXMNVGPOUKRXYILSCNLCTHCSENDXOIGWMTDPIUUAVDGSBQNDSVMYLSCTMRCMPBHNXWQIGCLKUFKRACWGDGJKOGRTTGWLCIXIZCFXSQPYQMQMPTDRTIFMTARDUFSRWCOCDUSMMVEESFBBFFRUMGBQYWWMFSIMIIXIDVHQWVDPHFNPUWDTCKUMOGAZNYZOBKRYZJTLTRHHJATNWYKYCEXIUTOFUOZOXUDUEYBMNQTMUZFCXIFZFMFVBVYCXONJJIBHHFSYRGLCKDPRGXGDHMATIATDGTPUPAINPKUHAHOWDCUNUBPQSNXPCJMBJTYPCOIJGCLZLJUAEDREFQBITUYJUFPCKWZNFKZRKHCETYLLBJDIVDAHWXEQQUFFCXYHYGELIPSUACOOKWCVURYTDSXBAKXZOKDHYJPLCUDTEFSCOCYNSGKIYRZENWBHTSRFFCEMSBOULZKYIDIFESVYXDXFGLYHDELFYBRTNXJTVUIVRMUXSCGHBWUKDEXYMMOHZAHQPPMCDOQBBMGYUNKWCIIJQHXYOCFEOHUPHSJKSWREATFCCUOPJNWMKASCSCPVVNLGGWCCFDQCHZKFIXBTEZOWAVXGRWPSCKBBETMEWGIIKCGPBZCERTRRNJZKCPRCJMWQCSSUYTKUZVFZMUBFLEPXXIYVVVOGINRQWKCMZYEFUTVBXUWNCZETLLFPUIWORGRLZFJMVUNEVVLMHEDDGKSYTYLGGRKVKHPADATKKLLTAOVGZPCDPCXDCGDQJMOMLOTIIRXEPRYXCPMNAWYFXUSHOKDPAVCENBNPUYKZJAGVRJZQFUMSFBTIRFSVYWLXSYWDFEAIQINEOWJUGBQBETPGMQZZODIDQOWNHUYURZELEFVSBPLZGFPVMNDUSBGEJOIXLEXBWHNKVAMWMLXDTZWYFZVLNGSEROQXOYZXCVJOWYBXZSKHELNDMXMHIBFUVBBEBIEPSPQFBKQUSGUAUDFCSBYLFYIUXREKIGCYYFBCDBRZECNDZGRDWAIDKSMCULRNIICFJFDJGNXVLMCTKIXQXPVAWFKXHSTFRUXMQLPVMEEKFKGVBXDIIMPDRUXQABVVKNQWENPTUYYCJOZXGFXJEZOYUJCNGHRTBPWPRFRFVQJLHKEHIYZXNOHZPVYSGNYAYFGWGHWCCYCDJZKUWKXQNTRTXFZKNPYTDAZBWQAPCZYGEOCLFGLFUZQMIMZAHYSXTPZIXSMNHDARHYKZAQCGUJVGFBVAIDNDUDEWPXJOLMOAHCLIKHFRGXHYOWOAMRQQMEIBNBYHWLTWAVNJINTXZHZEDHKTKGCIAFPWKWEKVGVKFEUBBGLETIRMBHJQMSUSGDISPGRJUTKGFWXOBPGBKAWCWUAVLIMYHFHMAPLGZRAOIWYZPXDQBVKPJISNNRFVOTANRCWCZGKFSVFKDNQOZAASPGVYTGIPRDEBOICEPVHJRCSPDPDHRTYZNOCUGDAWFSQRAOLYSQIXTGFXBXRVXMJFSNFYHEXWPHUCVMIZLNWDJQLVEFFDERMJVQCYDQKJGFUCQWAWXNUQNHXGVRVCUAQWRUNHEDQSSNXAPDVGRDSGIGYOGAMBQRZYIQGZLEDEYVUAUSACPIHDEDCTDTLDNNPJINTUSFGJJDRUQQZLWAQQSKHVJGMMMOTCXPNCOACRUBIQHCUKEFIPXIRENGDRSCMNGVHSYPIHJZKINCCVZTJTANUTWCDYSRGRENFBPPTSAMODACIIVDWDLEPCCPLJWATIFYBACOWGRWOUTQMOCSSVTWWIRULRYBGRTFFTALWPWVPABLNAGMSCPQGTZFTUWYYIVNOFFXADEHCFWCBSODYRJVQJFFBTASEGNOMJQSMBJMHJNJWUVLKDXYPEDJQMLWTWFIZZOMLBXHVZZFHTBMYRWSHKLKWAMDGBNCXGIIJVEQCDHAQCGWFPEKJCNYNHYRFTYNWQFCAHOZPOUFKYPHXBLRMLGOXVTKPXZDZCSZJCXDARCWOILEGCKECAXCLHIUSSZQLYQIWLJDWNTBESSPRERZFYWJNPOTDNIYPDEEVMCMPFQTRLRQHHDKAQBOSKAVTVBFHPPWSTISSGSZAXISHMSPPAYFMBYVYISQYITBVETPZWLBOQGAYBTTLBDCPHKDMYBTKNDTQXTWUGAUDUCZMWNUVZTSLIZNTWTNUTTXAFWQEBWDZGOSFSAABHFBFJUFLRSPARIBYYCGMDQJKUVHDUUFKITOCZEDWJBXDQXZVIYCFBRAJLULUZHCDEYHCUSECNCXOOFQQACSAIPTEALOFYMGCEOUBHAUCRIUTORHGSGZPOGRQUYHOICISUYZGCELDXWZAGEZIQTFSEVQVNDCHZLZEXLQLTPYBJRTLICGNDNHMOGZEWUVGKISEBAMCLBROJTIJZYZNTWCNOICNVJQVSDFOJUUSXYJVNXSKXGVJBHSVGDBVEHNAHAJHAWELALMILSOOAEKIZGMGRWSLAXNJXVNGLYJXROTKCGSYKYTEVZQMWEODRIBZIYXOPAZSUVIGWVDJIZWVDSYHLMDVFJSDQVNDXRMRUSEDMXAOUISQMGDBRRYCUQRORXNJYDZFLSKKDZDEQFRHBWFWOOQLYCFNETIVSZXPOUKPSJHAONOZDRNZAXUCTJOQNZDCMIXAOEOSDLRJYGJDIFGHROUFRLLDFEUVWNFHVTQRKKTMDLYDWCQWJLTXEZESVSWVAZLRPBNVMZQSLXLKSVZYVXHJBRNHGPTKSKRBMCISUTEFANPSEGMXNADBCHHBAOEVAKCPBMVGNXFAAECTFHJAVBEDXBTOLYFJLYKUOMYQNULMKTHMPPFOZWGUKFSILCIAYQVAYHOWXHGEDVZVIBQCBWHEJSYTDNZTEMAEDCPQIFDYUVCCBMYDMJGMTCLZGZHPWUHBETDKRIZGLXWALAJYDHUWBEIWFBQROYBDURARYHHNRHWGTMYCRUQBXYTIBTEUEJABMZWOTRTCHYXPECVYYXSZYVYPQNJRVZQUZFRBXTSWDNKAWXCRKHAZJJBNXOXLFFCLUEHTEWODGFPUQFWAGYLWLOTPGDTUVNSMQVKDFHXOZBCTIAEMNNYVJFEHZZYGKIRKKTTONQCOIBIRHUTNOBPTYENHOLPHIOVZARNHWSEORDMSIWOVBVPYFONLHBXGALLRZXWXINEMZZEUJGKCCEZLDGWOMDHSPNAZWJQZOMFWXCKFVJPQBNTAOZHCNZRABGHSEAYZYCINTCAAAJGWZGCPMPHFAMAXNYQCZWZCWLMXQFBMCJBYADMXWEUOUCKYOTLRFNQVYKSMDHYLZEEZHRIHRZUEEYAJOTWHZXHMPRXEDUXRPPHPMDMQBQXPEVLROIROKQRMUIFKQSBOGJYEXHVVJZOXMZDFOMNXDFXNVQLTCFBZSXXFMYKBJIRWARAIDUPBQDTONDXWSQYJFKIUWBVXHLNSYHGUPFQUXSOLWINNQWIRAZTPNIYAVEYURVKJFGEQMAHIEOKURMKTUZJQBSEOXWAUEMAQHYBNKUSJIDWBCKTVRJWOCLGCAZQMRDDULHNVFNGTHXRVEQWITQSMRGQIXXKBMFDISJSTMWVWDOSPZTRLLBBVCFQQTBSOPVTTNQZAJIOQBFUHJYBVSVFUQFBOVAFEIBOZOEXGRRJNLKOACELFOVLSEVWDOUSSOQABDVWLWWYWVYUVUXAXNOWQANTHVPVKPTYJJFRKANKBZEAIWZWBUDNTCYWVPKVSNUSVXBYOCERVSKBUVWUQWWBLSUQQBAPMQMEOTYFMSZVXLULKLOVMXTOUIMJPZPGVHSIQJTVCZTZXKQIEJQFUCTCYDXCUBESNPORTEOJFZXBRPQXDOYNCOIURIIWDCTKUSQASKWTZOMQANDJBZOGXXHWAZCYWIFWLGTWSSZXQDPYPSXSCYZRQYOMXCOILKCRQHWZDMTZJTFVKTIDYFZAJXBGGHLIPBJGFJHACPKYJPREOAWUFEQBVXDRHQIODBUNGBNXRSQKBVBRSEIEIWJYSPONGMMVQEBCFTQSLLYLISQMIYZOAJXMYEZXRERTERTTQUHMAVSMYHJEQIOMQUPURFIXBEOUURZUOOSFTXMHYSWDCHJYCRWDCAOQJZJRZAADMWELZPTCVBARAWWGLCVNEKHYPLEIYLKUWDBCZJQSKXHKPENTGTFNFOCRHVGZJZHNQOWOLLBRFJHDZYGRPGZANASIFVKCFSJEXZFPRMREAZTAVOARLLWSLGMZWWKPTCFOMGYMGIAGAPBTYTXFKVQJAAPBWIUASJBAHJNHWVTAXQGILJFTXRVHHJPVGHUZTZMWRRBIWVKRMVCRGITGLNDRIFYXZKZZFLNIHMSPUMZOJKWHIGIUFICOEPGJGUFKLZUKCFCJXWJCGDBSXZPOAWUZVPWTFSWXVSSNJBXGIMIHZINBXCMYRVWPGOJZQNCJFYXDEXZXNJVTWFQUYMSGHKJIUTDGGZXJSTGTIGQTRZIOJYVQUJSITSWNZJIFJUNIVICLIVYUPRXFDCSNCVJRDSPDEHENYUIGJEAJPXGWXRUNLVKWEJDIFDFFQFKXCIJPINAITZAOYWPEMGHVXQSZHIIEHITDXNUGGSRNSDKUAWKCMCZKELGSGUKHLNYOIVFHIWEHRAPAICWOCISZJFTGRGOWGYHUCYFCKAXVLYPITZCDPOUUYQJAITVGAGIZBZSTQNKYXOACVLJLYLYIQYDNFREMCZKYJPEBQFCRDWLICVLASTPKGHMZANJQZCLTUBZHXBLVRTZMZXTCTOZMEDAGFFQCQEBMQRNZLBWAMUNSEDOSKEIZEJGRXUHZZMXATUSWYYSFPLMJPUCGYNBOTDQJYGEQIGACCWVKTEMMJTAJPPYUADNPFJDEXJUIPJNFMMVVWWKTYBMRQCHWDKQDCVLZGNQDLTSKPUIISUITUGVYLAICSTYTACZGEDQBRBCPMDGGOWOCLVKKXMPWYXGJVIUSQSSGXXXKPLUDIUAOWTAZKKXDHIPZZUPRUKKLISDKHVLALASKSQVZYZFMVVFJSZXFSOQCJSZOLIGDCNOVWBIRWRQJEIRBBMEOTUCTTRIVUPZJRIJKIEWQOSRHHCBLQMWGQFSOSECYMOWRDKJNHXXWMJPWLLOGGVVVBPRNCQLIPUHRIKLONOZGSNDBAYRTQZGQFWFPVTZMAYRXOIJKXHEKRWDKDUMHRTZSKDYGIMIZTPHDQSJDFXCKANKZUBUBQZZPZTXDIIDDMKVVRQRVMYGTJLXLQDQNONJWWGOLGHGQHQTRZBVCYJGEFVKRJIYZOCZVCIAQFOAULOOQBDTGHICGFMNDCJGTQJFEEFDBSZOCZTZKYHAEZSYULKROMYLRWOKGNRQSKJGPTJFLZRZSUTVYOOIURSSFMOKANMTFGDZLJLLYZFXUNQAURHOPAJOZECXAMDZNCFFNVEDXGTZHNUJYORTYBXZRILGCSJMJAOFFSFTNNXXJUMXJZCBNPYZKECAKRFHDKZYPDAWR", 2666)); // 2809
    }
}
